export const ADD_PROFILE = 'ADD_PROFILE';
export const CANCEL_FORM = 'CANCEL_FORM';
export const ADD_PROFILE_TO_STORE = 'ADD_PROFILE_TO_STORE';
export const SUBMIT_FALSE = 'SUBMIT_FALSE';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';
export const GET_PROFILES = 'GET_PROFILES';
