version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18
jobs:
  build:
    working_directory: ~/todo_test
    docker:
      - image: node:10.15.3
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run: aws s3 sync ./build/ s3://to-do-test
      
workflows:
    build:
      jobs:
        - build
        - deploy:
            requires: 
              - build
